export default {
  SIGN_UP_LABEL: "SIGN UP",
  SIGN_UP_TEXT: "for a HEARBK account.",
  EMAIL_ADDRESS: "EMAIL ADDRESS",
  DISPLAY_NAME: "DISPLAY NAME",
  USERNAME: "USERNAME",
  PASSWORD: "PASSWORD",
  REPEAT_PASSWORD: "REPEAT PASSWORD",
  CREATE_ACCOUNT: "CREATE ACCOUNT",
};
