export default {
    SUBCONTAINER1_LABEL: "PROFILE SETTINGS",
    SUBCONTAINER1_SUBLABEL1: "DISPLAY NAME",
    SUBCONTAINER1_PLACEHOLDER1: "Display name",
    SUBCONTAINER1_SUBLABEL2: "USERNAME",
    SUBCONTAINER1_PLACEHOLDER2: "Username",
};