import React from 'react';
import './profileSettings.style.scss'

const PrivacyPolicy = () => {
    return (
        <section>
            <h1 class="c11" id="h.rp5ip5l68rls"><span class="c4 c7">HEARBK INC. PRIVACY POLICY</span></h1>
            <p class="c2"><span class="c8">HEARBK Inc.</span><span class="c0">&nbsp;(sometimes referred to as &ldquo;Company&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) is committed to providing you with privacy protection.</span></p>
            <p class="c1"><span class="c3 c4">General &ndash; Consent to Use and Sharing of Information Collected</span></p>
            <p class="c2"><span class="c0">The purpose of this Privacy Policy (the &ldquo;Policy&rdquo;) is to help you understand the kinds of personal and non-personally identifiable information we may gather about you when you visit our Application (&ldquo;App&rdquo;), or use any of the services offered on the App, how we may use or share that information in our business, the manner in which we will disclose the information to third-parties, how you can correct and/or update your personal information and how you can notify us that you no longer wish for us to use any of your personal information.</span></p>
            <p class="c2"><span class="c0">Please note that by using the App (and the services offered on the App), you signify your agreement with this Policy and consent (i.e. opt-in) to our collection, and use of personal information and non-personally identifiable information about you as described in this Policy. IF YOU DO NOT AGREE TO THE TERMS OF THIS POLICY, PLEASE DO NOT USE THE App OR ITS SERVICES OR PROVIDE US WITH PERSONAL INFORMATION ABOUT YOU.</span></p>
            <p class="c2"><span class="c0">Please note that the Policy applies only to the App and its services, but not to other websites to which we may link, or to third parties or advertisers on the App or to third-parties or advertisers in e-mails that we may send to you. Additionally, your use of the App and App&#39;s services is governed by all applicable laws, the App&rsquo;s Terms of Use, as well as by any other published rules pertaining to either the App or applicable service.</span></p>
            <p class="c1"><span class="c3">Types of Information We Collect</span><span class="c9">&nbsp;</span><span class="c3 c4">Personal Information We Collect</span></p>
            <p class="c2"><span class="c0">Personal information is any information that can be used to identify a specific individual such as your name, email address, home or business address, phone number, link to your website, information about your business, studio, audio files, equipment list, credit information, reviews, commentary, tutorials, articles or any photos that you may post on the App (collectively &ldquo;Submissions&rdquo;). We collect personal information about you from publicly available sources. We also collect personal information from you explicitly, and only when you voluntarily provide it to us or in instances in which you must provide such information in order to participate in activities on the App. By way of example only, you will provide personal information to us when you register to use the App, when you use the features of the service, including surveys, reviews, commentary, information provided in the knowledge section of listings, message boards or chat rooms, when you fill out a form, consummate transactions, or enter into contests, drawings or surveys, or when you otherwise contact us via email.</span></p>
            <p class="c1"><span class="c3 c4">Non-Personally Identifiable Information We Collect</span></p> <p class="c2"><span class="c0">When you visit the App and interact with the services and tools that reside here, we and third parties which provide services to us may collect non-personally identifiable information pertaining to your actions. This &quot;non-personally identifiable information&quot; that we collect includes information such as how many users log on to the App on a daily basis or view a particular article or advertisement. This type of information may be automatically collected from you in connection with your use of the App and the services offered on the App, and is generally collected from two sources &ndash; (i) your IP address on the server log files; and (ii) cookies.</span></p>
            <p class="c1"><span class="c3 c4">IP Address</span></p> <p class="c2"><span class="c0">Your IP address is a number that is assigned by your ISP (Internet Service Provider) to your computer to identify its location. We use your IP address to help diagnose problems with our server and to administer our website.</span></p>
            <p class="c1"><span class="c3 c4">Cookies and Web Beacons</span></p>
            <p class="c2"><span class="c0">The App uses a feature of your browser to set a &quot;cookie&quot; on your devices. Cookies are small packets of information that the App&rsquo;s computer stores on your device. The information in the cookie is transmitted from your computer to us, our agents, or to one of our third-party authorized service contractors and business partners or advertisers. The information contained in these cookies makes it possible for us to know if you are presently logged onto the App or whether you have done so in a prior visit. This technology also enables us to instantly determine your access privileges while allowing you to navigate the App or any of the App&rsquo;s services without your having to repeatedly log in.</span></p>
            <p class="c2"><span class="c0">Cookies from us and/or one of our authorized service contractors or business partners or advertisers are also used to collect standard information transmitted from your web browser including, without limitation: your Internet protocol address, browser type, web pages you visited with date and time, purchases you made from us on the App and the type of operating system on your device. This information is used to help us understand and meet the ever-changing needs and interests of our visitors and members.</span></p>
            <p class="c2"><span class="c0">We may also use cookies to track your access to, and use of the bulletin boards on the App, as well as your responses to any of our online surveys. We do not control any cookies you may receive from a third-party business partner or advertiser on the App and these cookies are not subject to this Policy, although the third-party business partner or advertiser may have their own policy.</span></p>
            <p class="c2"><span class="c0">We also use web beacon technology to help track site usage. Web beacons (also called single pixel gifs or action tags) allow us to track page viewing counts and patterns which we use to focus and tailor future content development, measure the effectiveness of our own marketing campaigns and assist with broadband capacity management for the App. We also may employ web beacons within the context of certain emails in order to determine the effectiveness and appeal of those mailings. These web beacons &#39;sense&#39; and notify us if and when you open the email, if your email program is capable of displaying HTML messages, and where you may navigate within these HTML messages.</span></p>
            <p class="c2"><span class="c0">You may modify your browser preference to provide you with choices relating to cookies. You have the choice to accept all cookies, to be notified when a cookie is set or to reject all cookies. If you choose to reject cookies you may be unable to use the App&rsquo;s services that require registration in order to participate or will have to sign in each time you visit the App.</span></p>
            <p class="c1"><span class="c3 c4">How We Use the Information We Collect</span></p>
            <p class="c2"><span class="c10">HEARBK</span><span class="c0">&nbsp;keeps your personal information private and, except as stated under Paragraph 4 of this Policy, will not share it with any third parties without your consent. We use the information collected, including personal information, for a variety of purposes. For example, we use your information to better understand your needs and provide you with better products and services. We may use your information to respond to your inquiries or requests, communicate with you, update you via email on products, services and benefits, alert you via email to promotional offers, personalize the App for you, contact you via email for market research, provide you via email with marketing information, newsletters or other information we think would be of particular interest. By providing us with your personal information, you expressly consent to our use of this personal information for these purposes.</span></p>
            <p class="c1"><span class="c3">When Do We Share the Information We Collect</span><span class="c9">&nbsp;</span><span class="c3">All Information</span><span class="c9">&nbsp;</span><span class="c3 c4">Service Providers</span></p>
            <p class="c2"><span class="c0">We may share your personal information and/or aggregate information with our listeners, affiliates, technical consultants, third party auditors and other third parties who work with us to create or maintain the App, enhance its functionality or provide associated services and/or deal with you in processing your orders and/or delivering content, samples, products, services and gifts and prizes.</span></p>
            <p class="c1"><span class="c3 c4">Compliance with Law</span></p>
            <p class="c2"><span class="c0">We reserve the right to access and/or disclose personal information and aggregate information we gather, as required by courts or administrative agencies and to the extent required to permit us to investigate suspected fraud, harassment or other violations of any law, rule or regulation, the Website&#39;s rules or policies, or the rights of third parties or to investigate any suspected conduct which we deem to be improper.</span></p>
            <p class="c1"><span class="c3 c4">Disclosure of Information in the Event of Merger or Sale of Assets</span></p>
            <p class="c2"><span class="c0">Company, its parent, subsidiaries or affiliates, could merge with or be acquired by another business entity, or all or substantially all of their respective assets could be acquired, or the assets of this App could be acquired or transferred to another business entity. Should such a combination, acquisition, transaction or transfer occur, we reserve the right to transfer some or all of your personal information, non-personally identifiable information and other information to our successors in business and purchasers (in whole or in part) of this Application&rsquo;s assets.</span></p>
            <p class="c1"><span class="c3 c4">Knowledge Section and Commentary</span></p>
            <p class="c2"><span class="c0">Among the many services we offer on the App, we provide voluntary reviews, message boards, comments, chat rooms and/or other interactive forums. Please be aware that we make no commitment to monitor these forums. Furthermore, any information which you may post to a forum, including your personal information, will be disclosed and available to all users of that forum, and is therefore no longer private. By using the App, you agree that we are not responsible for any information that you disclose or communicate online in such forums, and any disclosures you make are at your own risk. We reserve the right to re-publish your postings (in whole or part), taken from the application, comments or reviews anywhere on the App or elsewhere on the Web in any format or any other medium, including print and radio, and may include the author&rsquo;s Website member name, without prior notice or your express consent.</span></p>
            <p class="c1"><span class="c3 c4">Non-Personally Identifiable Information &ndash; Targeted Advertising</span></p>
            <p class="c2"><span class="c0">We believe that advertising on the Internet is more interesting to the user when it is relevant. Therefore, through the use of technologies such as cookies, we and our third-party business partners and advertisers may collect non-personally identifiable information about you and deliver advertisements that are targeted towards your particular interests and your behavior on the Internet. This is sometimes called behavioral advertising.</span></p>
            <p class="c2"><span class="c0">Our advertising is currently served in part by third party business partners or advertisers which deliver a cookie to you so the ads you see can be tracked and ensure that you are not shown the same ad too many times. Since the third party business partners or advertiser only tags your device with a number, they know nothing about who you are. We do not provide these third party business partners and advertisers with any personal information. However, these companies may use non-personally identifiable information about your visits to the Website and other sites with which they have arrangements in order to provide advertisements about goods and services of interest to you.</span></p>
            <p class="c2"><span class="c0">As described above, advertising may be delivered to you based upon the non-personally identifiable information you have provided to us (such as your interests and demographic data) and non-personally identifiable information we collect ourselves from you (such as the pages you have viewed on the Website or articles you have accessed). For instance, if you expressed an interest in cosmetics or have been reading material on the App about cosmetics, we may serve advertisements specifically to you regarding this topic. These targeted advertisements may also appear on the web sites of our third-party business partners and advertisers which are not owned or controlled by Company.</span></p>
            <p class="c2"><span class="c0">If you do not want to receive such targeted advertisements, then follow the instructions in the section titled &quot;Cookies&quot; on modifying your browser settings relating to cookies.</span></p>
            <p class="c1"><span class="c3 c4">Co-branded and Other Affiliated Sites</span></p>
            <p class="c2"><span class="c0">Certain information or services offered or provided through the App may, from time to time, be provided on or through other websites operated by or in conjunction with third parties (&quot;Partners&quot;). These websites and their features may have the same &quot;look and feel&quot; as the App. We term these websites &quot;co-branded sites&quot;, and oftentimes a Partner&#39;s logo or name may appear, or the Partner&#39;s name may be part of the URL. We may retain any personal information collected about you from one of these co-branded sites and such information from the co-branded site may also be retained by that Partner. Use of any such information will be subject to the privacy practices and policies as stated on the co-branded site, which may reference this Policy for our use of the information and the privacy practices and policies of our Partner with respect to the Partner&rsquo;s use of the information.</span></p>
            <p class="c1"><span class="c3 c4">Third Party Links</span></p>
            <p class="c2"><span class="c0">We do not monitor, control or endorse the information collection or privacy practices of any third parties including, without limitation, any Partner, advertiser or other third party that may provide services on the App. On behalf of various sponsors, the Web Site may provide sponsored links to third-party websites or resources (&quot;Linked Sites&quot;). We neither control nor have we reviewed or approved the content that appears on such Linked Sites. Even though certain information collected by such third parties might not identify you personally, we strongly encourage you to become familiar with their privacy practices, and to contact them if you have any questions about their respective privacy policies and practices.</span></p>
            <p class="c1"><span class="c3 c4">Security &ndash; How We Protect and Secure Your Personal Information and retain and destroy it.</span></p>
            <p class="c2"><span class="c0">We place a priority on the security of personal information, and we undertake reasonable security measures to protect the data that resides on our servers. We also use secure server software (SSL) to process all transactions which occur on the App. SSL encrypts your personal information transmitted over the Internet, including your credit card number, name and address. However, no security system is impenetrable. We cannot warrant or guarantee the security of its servers, nor can we guarantee that information supplied by Members or other users will not be intercepted while being transmitted over the Internet.</span></p>
            <p class="c2"><span class="c0">We store your personal information on our servers currently located at Atlanta, GA in the United States (and may change these locations) and, other than your Submissions and User Content (as defined in the Terms of Use), we use your personal information only for the period during which you are registered with our App and using our service. If you discontinue your account, other than our use of your Submissions on the Website, we will not use such personal information; however, even if you delete your account from our records, there will be residual information that will remain within our databases, access logs, and other records, which may or may not contain personal information. In addition, we are not responsible for updating or removing any information contained in third-party lists or databases.</span></p>
            <p class="c1"><span class="c3 c4">Correction/Updating Personal Information and Opt-Out</span></p>
            <p class="c2"><span class="c0">If your personal information changes (such as your address, zip code), or if you no longer desire to use or access the App or any of our services or receive any emails from us, we encourage you to correct, update or remove the personal information that you provided. This can be done at the &quot;Edit Profile&quot; page for the App. Also, in each email that we send to you, you can opt-out of receipt of future emails.</span></p>
            <p class="c1"><span class="c3 c4">How to Contact Us</span></p>
            <p class="c2"><span class="c0">If you have questions about this Policy or anything else regarding our use or sharing of your personal information or information about us, you can send any inquiries to us at admin@hearbk.com, or send us a letter to the following address: HEARBK Inc., 741 Monroe Dr NE, Atlanta, GA 30308, USA.</span></p>
            <p class="c1"><span class="c3 c4">Privacy Policy Changes</span></p>
            <p class="c2"><span class="c0">If we make changes to any of the terms or conditions of the Policy, this document will be revised so that you will always know what information we gather, how we might use that information and to whom we will disclose it. We reserve the right to revise, modify, add, amend or remove (&ldquo;change&rdquo;) portions of this Policy at any time so long as we notify you of a change via email or by posting notice of a change on the Website. In such case, any such changes will become effective immediately upon such notice unless we advise you otherwise. Your continued use of the App and the services offered on the App after this Policy has been changed shall be deemed to be your continued acceptance of the terms and conditions of the Policy, as changed. We encourage you to review this Policy regularly.</span></p>
            <p class="c1 c6"><span class="c4 c5"></span></p>
            <p class="c1 c6"><span class="c4 c5"></span></p> <p class="c1 c6"><span class="c4 c5"></span></p>
        </section>
    )
}

export default PrivacyPolicy;