import React from 'react';
import './profileSettings.style.scss'

const TermServices = () => {
    return (
        <section>
            <h1 class="c7" id="h.ea5o0skkvk1w"><span class="c3">HEARBK TERMS AND CONDITIONS OF USE</span></h1>
            <h3 class="c7" id="h.bj5e261unguf"><span class="c10 c11">USE OF THIS APPLICATION SIGNIFIES YOUR UNDERSTANDING OF, AND AGREEMENT TO COMPLY WITH, THESE TERMS AND CONDITIONS OF USE</span></h3>
            <p class="c1"><span class="c0">By using this Application, you have entered into a binding agreement to comply with the following terms and conditions of use (&ldquo;Terms of Use&rdquo;).</span></p>
            <p class="c1"><span class="c0">If you do not agree to these Terms of Use, you have no right to use this Application in any way. For purposes of this agreement, the terms &ldquo;HEARBK,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; and &ldquo;our&rdquo; refer to HEARBK, Inc.. The terms and &ldquo;you&rdquo; and &ldquo;your&rdquo; refers to you, as a user of this Application.</span></p>
            <p class="c1"><span class="c0">PLEASE READ THESE TERMS OF USE CAREFULLY. THEY AFFECT YOUR LEGAL RIGHTS</span></p>
            <p class="c1"><span class="c4">Modifications of the Terms of Use</span></p>
            <p class="c1"><span class="c0">We reserve the right to modify these Terms of Use at any time by adding new terms or amending existing terms. Such modifications will be effective as of the date that the updated Terms of Use are posted on the Application (&ldquo;Effective Date&rdquo;). Your use of the Application after the Effective Date, constitutes your acknowledgment of such modifications and your agreement to be bound by the Terms of Use as modified. If you do not accept such modifications, do not continue to use the Application. HEARBK shall provide notice to you of such modifications before the Effective Date by email to the last email address that you gave us. The Terms of Use cannot be modified orally by any HEARBK employees or service representatives.</span></p>
            <p class="c1"><span class="c4">Privacy and Protection of Personal Information</span></p>
            <p class="c1"><span class="c0">Our Privacy Policy is hereby incorporated by reference in its entirety and is available at https://HEARBK.com/pages/privacy.</span></p>
            <p class="c1"><span class="c4">Application of U.S. Law</span></p>
            <p class="c1"><span class="c0">By entering this Application, you acknowledge that HEARBK intends this Application only to be construed in accordance with United States law. HEARBK makes no representations that materials on this Application are appropriate for use outside the United States or intended to comply with any law other than U.S. law. If you use this Application from outside the United States, you do so at your own risk and you are responsible for compliance with all local laws and regulations, including without limitation applicable laws and regulations concerning the transmission of data.</span></p>
            <p class="c1"><span class="c0">Personal and Non-Commercial Limited License</span></p>
            <p class="c1"><span class="c0">HEARBK hereby grants you a limited, revocable, non-exclusive, non-transferable license, without any right to sublicense, to use this Application solely for your own personal use and not for republication, distribution, assignment, sublicense, sale, preparation of derivative works, or other use. Commercial use of any content on the Application is absolutely forbidden. You agree not to copy materials, content or any other information on the Application, reverse engineer or break into (hack) the Application, or use materials, products or services in violation of any state or federal law. You are solely responsible for the audio, video, information, opinions, descriptions, photos, profiles, messages, comments, reviews, tutorials, articles and all other content that you upload, publish, or display on or through the Application, or transmit to or share with other users (&ldquo;User Content&rdquo;). By posting User Content to any part of the Application, you automatically grant HEARBK an irrevocable, perpetual, non-exclusive, transferable, royalty-free, worldwide license to use, copy, publicly perform, publicly display, reformat, translate, excerpt, transmit, and distribute such User Content for any purpose on or in connection with the Application or the promotion thereof, to prepare derivative works of, or incorporate into other works, such User Content, and authorize sublicenses of the foregoing. In addition, you shall not manipulate or otherwise display the Application by using framing or similar navigational technology, nor shall you access the Application by any means other than through the standard industry-accepted interfaces.</span></p>
            <p class="c1"><span class="c4">Trademarks, Copyright and Proprietary Rights</span></p>
            <p class="c1"><span class="c0">The HEARBK mark and logos are trademarks of HEARBK. Nothing herein shall be construed as granting, by implication, estoppel, or otherwise, any license or right to use HEARBK&rsquo;s name, logos, or trademarks without obtaining the written permission of HEARBK.</span></p>
            <p class="c1"><span class="c0">All content on the Application, including but not limited to designs, data and databases, text, graphics, images, photographs, illustrations, audio and video material, artwork, proprietary information, client-side code (e.g. HTML, JavaScript, etc.),server-side code (e.g. active server pages, VBScript, databases, etc.), information and statistics concerning the use of the Application, and all copyrightable elements of the Application, and their selection and arrangement (excluding any of User Content) (the &ldquo;Site Content&rdquo;) individually and/or collectively, are the proprietary property of HEARBK and is protected by U.S. copyright law, international treaties and other intellectual property rights. Except as otherwise stated therein, Site Content may not be copied, transmitted, displayed, performed, distributed (for compensation or otherwise), licensed, altered, framed, stored for subsequent use or otherwise used in whole or in part in any manner without HEARBK&rsquo;s prior written consent, except to the extent permitted by the Copyright Act of 1976 (17 U.S.C. &sect;107), as amended, and then, only with notices of HEARBK&rsquo;s proprietary rights, provided however, that you may download the information and print out hard copies for your own personal, non commercial use, so long as you do not remove any copyright or other notice as may be contained in the information as downloaded.</span></p>
            <p class="c1"><span class="c4">No Unlawful or Prohibited Use</span></p>
            <p class="c1"><span class="c0">As a condition of your use of the Application, you will not use the Application for any purpose that is unlawful or prohibited by these Terms of Use. Without limiting the foregoing, you will not provide any information that is false or misleading or hides your identity or violates obligations of confidentiality to any third party or violates local rules and regulations concerning offensive or unacceptable User Content.</span></p>
            <p class="c1"><span class="c0">You may not use the Application in any manner which could damage, disable, interrupt, overburden, or impair the Application or HEARBK&rsquo;s network or servers, or interfere with any other party&rsquo;s use and enjoyment of the Application. You may not attempt to gain unauthorized access to the Application, other accounts, computer systems or networks connected to the Application, through hacking, password mining or any other means. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available through the Application. In addition, you shall not register, subscribe, attempt to register, attempt to subscribe, unsubscribe, or attempt to unsubscribe, any party for the Application if you are not expressly authorized by such party to do so.</span></p>
            <p class="c1"><span class="c4">Intended Audience</span></p>
            <p class="c1"><span class="c0">This Application is intended for adults age 18 or older. This Application is not intended for any children under the age of 13.</span></p>
            <p class="c1"><span class="c4">Application Availability</span></p>
            <p class="c1"><span class="c9 c10">HEARBK</span><span class="c0">&nbsp;will make reasonable efforts to keep the Application operational. However, events of force majeure (including without limitation, natural disasters, government regulation, strikes, acts of war and terrorism), certain technical difficulties, routine site maintenance/upgrades and other events outside the control of HEARBK may, from time to time, result in interruptions to the Application. In addition, HEARBK reserves the right at any time and from time to time to modify or discontinue (on a temporary or permanent basis) certain functions of the Application or the entire Application, with or without notice.</span></p>
            <p class="c1"><span class="c4">Commentary</span></p>
            <p class="c1"><span class="c0">This Application may include articles and commentary containing information in the form of news, reviews, opinions, articles, tutorials and/or comments (collectively &ldquo;Commentary&rdquo;) that, unless otherwise stated therein, should not be construed as specific advice or instruction from HEARBK or official expressions of HEARBK. HEARBK does not warrant, either expressly or by implication, the factual accuracy of the Commentary posted, nor does it adopt any statement as its own, or warrant any Commentary offered by the author of the same.</span></p>
            <p class="c1"><span class="c0">If you provide Commentary to the Application, HEARBK reserves the right to moderate, edit, and remove any of your Commentary that HEARBK deems in its sole discretion to have been submitted in bad faith or with malice or is otherwise in violation of law or the rights of others.</span></p>
            <p class="c1"><span class="c4">Do Not Call Registry Compliance</span></p>
            <p class="c1"><span class="c0">By submitting personal contact and/or financial information to HEARBK through this Application, you hereby grant written permission to HEARBK to contact you by telephone, mail, and/or e-mail and therefore waive any right to file a claim in any type of civil action, with the United States Federal Trade Commission or any other governmental agency in reference to these calls or contacts.</span></p>
            <p class="c1"><span class="c4">Links to Affiliate Applications</span></p>
            <p class="c1"><span class="c0">This Application may contain links to websites controlled or offered by our partners and affiliates, which may contain terms and conditions that are different from these Terms of Use and privacy policies. You should read the terms and conditions and privacy policies on each such website, as your accessing such website constitutes your agreement to be bound by the terms and conditions and privacy policies contained in such website.</span></p>
            <p class="c1"><span class="c4">Third-Party Links</span></p>
            <p class="c1"><span class="c0">This Application may contain links to third-party websites that are not under the control of or maintained by HEARBK including advertiser websites (the &ldquo;Linked Sites&rdquo;). The Linked Sites are not under the control of HEARBK and HEARBK is not responsible for the contents of any Linked Site. HEARBK does not endorse or make any representations about these websites, or any information, materials, or products found thereon. If you access any of the third-party websites linked on this Application, you do so at your own risk. In no event shall HEARBK be liable for any loss, claim, damages, or costs that may arise in connection with your use any third-party links or Linked Sites.</span></p>
            <p class="c1"><span class="c0">Any dealings with third parties (including advertisers) included within the Application or Linked Sites or participation in promotions offered by third parties, including the delivery of and payment for goods and services, and any other terms, conditions, warranties or representations associated with such dealings or promotions, are solely between you and the advertiser or other third party. HEARBK shall not be responsible or liable for any part of any such dealings or promotions.</span></p>
            <p class="c1"><span class="c4">Third-Party Materials on the Application</span></p>
            <p class="c1"><span class="c0">This Application may contain materials submitted by third-parties, including but not limited to User Content and advertisements. HEARBK has not tested or evaluated these materials and does not endorse or make any representations about these materials or your use thereof. If you use any of the third-party materials, you do so at your own risk. In no event shall HEARBK be liable for any loss, claim, damages, or costs that may arise in connection with your use of these materials.</span></p>
            <p class="c1"><span class="c4">Indemnification</span></p>
            <p class="c1"><span class="c0">You agree to indemnify, defend and hold harmless HEARBK, it officers, managers, members, employees, agents, attorneys, affiliates, successors and assigns, from and against any liability, loss, claim, investigation, settlement, judgment, proceeding, cost and expense, including without limitation reasonable attorneys&rsquo; fees and disbursements, whether or not a lawsuit or other proceeding is filed, that in any way arises out of or relates to (a) your breach or violation of these Terms of Use or any applicable state or federal law; or (b) your infringement of any copyright or intellectual property rights of any person or entity; or (c) your use of the Application. This provision shall survive the termination of these Terms of Use for any reason.</span></p>
            <p class="c1"><span class="c4">Disclaimer</span></p>
            <p class="c1"><span class="c0">THE INFORMATION ON THIS APPLICATION IS PROVIDED ON AN &ldquo;AS IS,&rdquo; &ldquo;AS AVAILABLE&rdquo; BASIS WITHOUT ANY WARRANTIES OF ANY KIND. YOU AGREE THAT USE OF THIS WEBSITE IS AT YOUR SOLE RISK. HEARBK DISCLAIMS ALL WARRANTIES OF ANY KIND, INCLUDING BUT NOT LIMITED TO ANY EXPRESS WARRANTIES, STATUTORY WARRANTIES, AND ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THIRD PARTY RIGHTS ARISING OUT OF COURSE OF CONDUCT OR TRADE CUSTOM OR USAGE.</span></p>
            <p class="c1"><span class="c0">HEARBK MAKES NO WARRANTIES OF ANY KIND THAT THE APPLICATION WILL MEET YOUR REQUIREMENTS OR OPERATE IN A TIMELY, SECURE, UNINTERRUPTED MANNER OR THAT ANYTHING GENERATED BY OR OBTAINED FROM THE APPLICATION WILL BE ACCURATE OR RELIABLE OR THAT ANY ERRORS WILL BE CORRECTED.</span></p>
            <p class="c1"><span class="c0">HEARBK HAS NO LIABILITY WHATSOEVER FOR YOUR USE OF THE APPLICATION OR USE OF ANY INFORMATION OR SERVICES ACCESSED THROUGH THE APPLICATION INCLUDING WITHOUT LIMITATION ANY DAMAGE TO YOUR COMPUTER SYSTEMS OR LOSS OF DATA OR OTHERWISE THAT RESULTS FROM YOUR USE OF THE APPLICATION.</span></p>
            <p class="c1"><span class="c0">NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM HEARBK THROUGH THE APPLICATION SHALL CREATE ANY WARRANTY, REPRESENTATION, OR GUARANTEE OF ANY KIND.</span></p>
            <p class="c1"><span class="c0">Some states or other jurisdictions do not allow the exclusion of implied warranties, so the above exclusions may not apply to you if prohibited by law.</span></p>
            <p class="c1"><span class="c0">Limitation of Liability</span></p>
            <p class="c1"><span class="c0">UNDER NO CIRCUMSTANCES WILL HEARBK BE LIABLE OR RESPONSIBLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL (INCLUDING WITHOUT LIMITATION DAMAGES FROM LOSS OF BUSINESS, LOSS OF GOODWILL, LOSS OF USE OR DATA OR OTHER INTANGIBLE LOSSES, LOSS OF ACTUAL OR ANTICIPATORY PROFITS, LITIGATION, OR INABILITY TO USE THE WEBSITE OR UNAUTHORIZED ACCESS TO, OR ALTERATION OF, YOUR DATA OR STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE WEBSITE OR ANY OTHER MATTER RELATING TO THE WEBSITE), SPECIAL, EXEMPLARY, PUNITIVE, OR OTHER DAMAGES, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN ANY WAY RELATING TO THE APPLICATION, YOUR APPLICATION USE, OR THE CONTENT OR MATERIALS IN THE APPLICATION, HEARBK&rsquo;S EXERCISE OF ITS RIGHTS TO MODIFY, LIMIT, OR DELETE MATERIALS IN YOUR LISTINGS ON THE APPLICATION, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. YOUR SOLE AND EXCLUSIVE REMEDY FOR DISSATISFACTION WITH THE APPLICATION AND/OR CONTENT IS TO CEASE ALL OF YOUR APPLICATION USE.</span></p>
            <p class="c1"><span class="c0">Some states and other jurisdictions may not allow this limitation of liability, so the foregoing disclaimer may not apply to you if prohibited by applicable law.</span></p>
            <p class="c1"><span class="c4">Waiver of Jury Trial/Rights to Class Actions</span></p>
            <p class="c1"><span class="c0">BY ACCEPTING THESE TERMS OF USE YOU ACKNOWLEDGE THAT YOU ARE WAIVING YOUR RIGHT TO A JURY TRIAL AND ANY RIGHTS YOU MAY HAVE TO BRING ANY CLAIMS ON A CLASS, REPRESENTATIVE, CONSOLIDATED OR MASS ACTION BASIS.</span></p>
            <p class="c1"><span class="c0">Copyright Infringement Notice Policy</span></p>
            <p class="c1"><span class="c0">The Digital Millennium Copyright Act of 1998 (the &ldquo;DMCA&rdquo;) provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If you believe that your copyrighted material has been copied in a way that constitutes copyright infringement, please contact HEARBK&rsquo;s designated Copyright Agent and provide the following information:</span></p>
            <p class="c1"><span class="c0">&bull; A description of the copyrighted work that allegedly has been infringed.</span></p>
            <p class="c1"><span class="c0">&bull; A description of the material that is claimed to be infringing and the profile name of where such material is located on the Application, sufficient to permit HEARBK to locate the material.</span></p>
            <p class="c1"><span class="c0">&bull; Your contact information, including an address, telephone number, and e-mail address.</span></p>
            <p class="c1"><span class="c0">&bull; A statement by you that you have a good faith belief that the disputed use of copyright-protected material in the manner complained of is not authorized by the copyright owner, its agent, or the law.</span></p>
            <p class="c1"><span class="c0">&bull; A statement, under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or are authorized to act on the copyright owner&rsquo;s behalf.</span></p>
            <p class="c1"><span class="c0">&bull; Your physical or electronic signature.</span></p>
            <p class="c1"><span class="c0">Send this information to:</span></p>
            <p class="c1"><span class="c0">By mail:</span></p>
            <p class="c1"><span class="c0">HEARBK, Inc. &nbsp;Attn: Copyright Agent &nbsp;741 Monroe Dr NE, Atlanta, GA &nbsp;30308, USA</span></p>
            <p class="c1"><span class="c0">By email:</span></p>
            <p class="c1"><span class="c0">admin@HEARBK.com</span></p>
            <p class="c1"><span class="c0">You should consult your legal advisor before filing a notice or counter-notice. Also, be aware that there can be penalties for false claims under the DMCA.</span></p>
            <p class="c1"><span class="c4">Choice of Law</span></p>
            <p class="c1"><span class="c0">These Terms of Use shall be construed under and enforced by the laws of the State of Georgia, application of its principles of conflict of laws.</span></p>
            <p class="c1"><span class="c4">Consent to Receive Notices Electronically</span></p>
            <p class="c1"><span class="c0">You consent to receive from us any notices, disclosures and other communications (collectively &ldquo;Notices&rdquo;), to which these Terms of Use refer, electronically, including without limitation by email, posting Notices on the Application, or other electronic communication technology that may hereafter be developed. You agree that all Notices that we provide to you electronically satisfy any legal requirements that such communications be in writing. To withdraw your consent to receive Notices electronically, you must notify us of your withdrawal of such consent by communicating to us at admin@HEARBK.com, and discontinue your use of this Application. In such event, all rights granted to you pursuant to these Terms of Use, including, without limitation, the licenses to use the Application set forth above, shall automatically terminate. &nbsp;Also, please note that your consent to receive notices is separate from any election that you make with respect to receipt of marketing communications, which is discussed under the Privacy Policy.</span></p>
            <p class="c1"><span class="c4">Termination/Access Restriction</span></p>
            <p class="c1"><span class="c0">These Terms of Use shall remain in full force and effect while you use the Application. HEARBK may restrict, suspend, or terminate your access to all or any part of our Application at any time and for any reason without notice or liability to you, including without limitation your breach of any of these Terms of Use, violation of the rights of third parties, failure to update or keep your information current.</span></p>
            <p class="c1"><span class="c0">HEARBK also has the right to refuse, move, limit the size of data in, or remove, any material that you submit on or through the Application, and to establish general practices and limits concerning use of the Application. HEARBK reserves the right to exercise whatever means it deems necessary to prevent unauthorized access to the Application, including but not limited to, technological barriers, IP mapping, and direct contact with your Internet service provider. Upon termination of your access to the Application, HEARBK shall delete all of your public User Content, without liability to you.</span></p>
            <p class="c1"><span class="c4">Assignment</span></p>
            <p class="c1"><span class="c0">These Terms of Use and our rights hereunder may be assigned, in whole or in part, by HEARBK to a third party, in our sole discretion, in connection with a merger, acquisition, reorganization or sale of substantially all of our assets, or otherwise, in whole or in part. You may not assign, sublicense, or delegate any of your rights hereunder.</span></p>
            <p class="c1"><span class="c4">Severability</span></p>
            <p class="c1"><span class="c0">If any provision of these Terms of Use shall be adjudged by a court of competent jurisdiction to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms of Use will otherwise remain in full force and effect.</span></p>
            <p class="c1"><span class="c4">Contact</span></p>
            <p class="c1"><span class="c0">Any questions about these Terms of Use should be directed to admin@HEARBK.com</span></p>
            <p class="c1 c6"><span class="c4"></span></p>
            <p class="c1"><span class="c4">Opening an Account</span></p>
            <p class="c1"><span class="c0">To become a User and access the App and Services you must register for an &ldquo;Account.&rdquo; You agree to provide true, accurate and complete information as prompted by the registration form and all forms you access on the App, and to update this information to maintain its truthfulness, accuracy and completeness.</span></p>
            <p class="c1 c6"><span class="c0"></span></p>
            <p class="c1"><span class="c4">Termination</span></p>
            <p class="c1"><span class="c10 c9">HEARBK</span><span class="c0">&nbsp;reserves the right to terminate the participation of any User without reason but expressly including any User that HEARBK judges to be in violation of the User Agreement. Without limiting the foregoing, HEARBK may terminate the participation of a User if we think that they are creating problems, legal liabilities (actual or potential), infringing someone else&rsquo;s intellectual property rights, engaging in fraudulent, immoral or illegal activities, or for other similar reasons. If you are a Premium member and your Premium account is terminated, any unused proposal credits will be foregone. Unused proposal credits are rolled over to the following months only as long as your account is in good standing.</span></p>
            <p class="c1"><span class="c4">Promotion</span></p>
            <p class="c1"><span class="c0">You agree and acknowledge that unless explicitly requested, HEARBK may display your company name, logo and public description of your projects and profile as part of the HEARBK website(s) and / or other HEARBK marketing materials.</span></p>
            <p class="c1 c6"><span class="c0"></span></p><p class="c1"><span class="c4">Taxes</span></p><p class="c1"><span class="c0">You are responsible for paying any taxes, including any goods and services or value added taxes for services you acquire or services you perform.</span></p>
            <p class="c1"><span class="c4">Feedback, Reputation and Reviews</span></p>
            <p class="c1"><span class="c0">You may not do (or omit to do) anything that may undermine the integrity of HEARBK&rsquo;s review or feedback system. We are entitled to suspend or terminate your membership at any time if we, in our sole and absolute discretion, are concerned by any feedback about you, or your feedback rating is considered to be problematic to HEARBK.</span></p>
            <p class="c1"><span class="c4">Other terms of use:</span></p>
            <p class="c1"><span class="c0">Users will not use any automated collection mechanism or any manual process to monitor or copy the web pages comprising the Site or the content or user data contained therein without the prior written permission of HEARBK.</span></p>
            <p class="c1"><span class="c0">Users will not distribute unsolicited commercial messages (&ldquo;spam&rdquo;) through the User&rsquo;s Account.</span></p>
            <p class="c1"><span class="c0">Users will not contact music creators or listeners through the App or through information gained from our App with the intent of subverting them from using our Services.</span></p>
            <p class="c1"><span class="c0">Users will not engage in personal attacks, negative or other unfair criticism or other forms of discourteous and unprofessional online conduct or practices.</span></p>
            <p class="c1"><span class="c0">Users will not attempt to contact other users they were introduced to through HEARBK directly, outside of HEARBK channels. Users will not create multiple user Accounts for any reason.</span></p><p class="c1"><span class="c4">Refund Policy</span></p>
            <p class="c8"><span class="c9">HEARBK maintains a &ldquo;No Refunds&rdquo; policy. &nbsp;However, for any unfulfilled feedback orders, HEARBK reserves the right to cancel orders and monies will subsequently be returned to the account of the buyer. &nbsp;The returned funds can be used to purchase feedback from other available users on the Application.</span></p>
            <p class="c5"><span class="c13"></span></p><p class="c5"><span class="c13"></span></p><p class="c5"><span class="c13"></span></p>
        </section>
    )
}

export default TermServices;