export default {
  PAYMENT_HEADER: "PAYMENT METHOD",
  NAME_ON_CARD: "NAME ON CARD",
  CARD_NUMBER_LABEL: "CARD NUMBER",
  CARD_NUMBER_PLACEHOLDER: "---- / ---- / ---- / ----",
  EXPIRY_DATE_LABEL: "EXPIRY DATE",
  EXPIRY_DATE_PLACEHOLDER: "-- / --",
  CVC_LABEL: "CVC",
  CVC_PLACEHOLDER: "---",
  SAVE_CARD_TEXT: "Save this card for future use",
};
