export default {
    COMMENTS_LABEL: `COMMENTS`,
    RATE_LISTENER: `rate listener`,
    LISTENER_RESPONSE_TIME: `LISTENER RESPONSE TIME`,
    SERVICE_AS_EXPECTED: `SERVICE AS EXPECTED`,
    BUY_AGAIN_OR_RECOMMEND: `BUY AGAIN OR RECOMMEND`,
    WRITE_YOUR_FEEDBACK: `Write your feedback`,
    SUBMIT_FEEDBACK: `SUBMIT FEEDBACK`,
    CANCEL_ORDER: `CANCEL ORDER`
};