export default {
  UPLOAD_TRACK_HEADER: "UPLOAD YOUR TRACK",
  TITLE_LABEL: "TRACK TITLE",
  TITLE_INPUT_PLACEHOLDER: "Type the title for your track",
  TRACK_GENRE_LABEL: "TRACK GENRES",
  TRACK_GENRE_PLACEHOLDER: "Search for genres",
  YOU_TUBE_LABEL: "PASTE YOUR YOUTUBE LINK",
  YOU_TUBE_LINK_PLACEHOLDER: "https://",
  FILE_TO_UPLOAD_LABEL: "Choose the file to upload",
  OR: "-- OR --",
  UPLOAD_YOUR_TRACK: "UPLOAD FROM DEVICE",
  ADD_YOUTUBE_URL: "UPLOAD FROM YOUTUBE",
  FAVOURITE_GENRES: [
    `Alternative Rock`,
    `Ambient`,
    `Blues`,
    `Classical`,
    `Country`,
    `Dance`,
    `EDM`,
    `Dancehall`,
    `Deep House`,
    `Disco`,
    `Drum Bass`,
    `Dubstep`,
    `Electronic`,
    `Folk`,
    `House`,
    `Hip-Hop`,
    `House`,
    `Indie`,
    `Jazz`,
    `K-Pop`,
    `Latin`,
    `Metal`,
    `Piano`,
    `Pop`,
    `Rap`,
    `R&B`,
    `Soul`,
    `Reggae`,
    `Reggaeton`,
    `Rock`,
    `Techno`,
    `Trance`,
    `Trap`,
    `Triphop`,
    `World`
  ],
  RATINGS_TEXT: "How many ratings would you like to receive?",
  RATINGS_TIER_10: "10 FOR $1",
  RATINGS_TIER_100: "100 FOR $5"
};
