export default {
    HEADER_A: `LISTENER`,
    HEADER_B: `PREFERENCES`,
    DESCRIPTION_A: `What type of feedback would you like to give?`,
    DESCRIPTION_B: `Select one or the other, or both.`,
    HIT_REQUESTS_TITLE: `HIT REQUESTS`,
    HIT_REQUESTS_LIS_A: `Rate tracks`,
    HIT_REQUESTS_LIS_B: `Earn points`,
    HIT_REQUESTS_LIS_C: `Get rewards`,
    PRO_REQUESTS_TITLE: `PRO REQUESTS`,
    PRO_REQUESTS_LIS_A: `Score tracks`,
    PRO_REQUESTS_LIS_B: `Give comments`,
    PRO_REQUESTS_LIS_C: `Make money`,
    DETAILS_TITLE: `YOUR DETAILS`,
    CITY_LABEL: `CITY`,
    CHOOSE_CITY: `Type city`,
    GENDER_LABEL: `GENDER`,
    GENDER: [
        `Male`,
        `Female`,
        `Non-Binary`
    ],
    DOB_LABEL: `DATE OF BIRTH`,
    DOB: `MM-DD-YYYY`,
    FAVOURITE_GENRES_LABEL: `FAVORITE GENRES`,
    FAVOURITE_GENRES_SEARCH: `Search for genres`,
    TAGS_LABEL: `TAGS`,
    TAGS_SEARCH: `Search for tags`,
    BUTTON_LABEL: `What would you like to do now?`,
    SAVE: `SAVE`,
    RATE_TRACKS_TEXT: `RATE NEW TRACKS`,
    ORDER_FEEDBACK_TEXT: `ORDER FEEDBACK`
};