export default {
    HEADER_A: `LISTENER`,
    HEADER_B: `PREFERENCES`,
    DESCRIPTION_A: `What type of feedback would you like to give?`,
    DESCRIPTION_B: `Select one or the other, or both.`,
    HIT_REQUESTS_TITLE: `HIT REQUESTS`,
    HIT_REQUESTS_LIS_A: `Rate tracks`,
    HIT_REQUESTS_LIS_B: `Earn points`,
    HIT_REQUESTS_LIS_C: `Get rewards`,
    PRO_REQUESTS_TITLE: `PRO REQUESTS`,
    PRO_REQUESTS_LIS_A: `Score tracks`,
    PRO_REQUESTS_LIS_B: `Give comments`,
    PRO_REQUESTS_LIS_C: `Make money`,
    DETAILS_TITLE: `YOUR DETAILS`,
    CITY_LABEL: `CITY`,
    CHOOSE_CITY: `Type city`,
    GENDER_LABEL: `GENDER`,
    GENDER: [
        `Male`,
        `Female`,
        `Non-Binary`
    ],
    DOB_LABEL: `DATE OF BIRTH`,
    DOB: `MM-DD-YYYY`,
    FAVOURITE_GENRES_LABEL: `FAVORITE GENRES`,
    FAVOURITE_GENRES_SEARCH: `Search for genres`,
    TAGS_LABEL: `TAGS`,
    TAGS_SEARCH: `Search for tags`,
    PRICE_LABEL: `PRICE`,
    PRICE_DESCRIPTION: `Set the amount you'd like to charge to rate and review one track.`,
    PRICE_PLACEHOLDER: `5`,
    SEND_ME_LABEL: `SEND ME`,
    SEND_ME_DESCRIPTION_A: `Tell users what you love listening to or what you may need at the moment.`,
    SEND_ME_DESCRIPTION_B: `"I'm looking for uptempo, sample free tracks for a new TV show." or "I'm open to listening to anything."`,
    SEND_ME_TITLE_A: `Send me`,
    SEND_ME_TITLE_B: `type something here`,
    BIO_LABEL: `BIO`,
    DESCRIBE_YOURSELF_TITLE: `Describe yourself here`,
    RATE_TRACKS_TEXT: `RATE NEW TRACKS`,
    ORDER_FEEDBACK_TEXT: `ORDER FEEDBACK`
};