export default {
    CITY_LABEL: `CITY`,
    CHOOSE_CITY: `Type city`,
    GENDER_LABEL: `GENDER`,
    GENDER: [
        `Male`,
        `Female`,
        `Non-Binary`
    ],
    DOB_LABEL: `DATE OF BIRTH`,
    DOB: `MM-DD-YYYY`,
    FAVOURITE_GENRES_LABEL: `FAVORITE GENRES`,
    FAVOURITE_GENRES: [
        `Alternative Rock`,
        `Ambient`,
        `Blues`,
        `Classical`,
        `Country`,
        `Dance`,
        `EDM`,
        `Dancehall`,
        `Deep House`,
        `Disco`,
        `Drum Bass`,
        `Dubstep`,
        `Electronic`,
        `Folk`,
        `House`,
        `Hip-Hop`,
        `House`,
        `Indie`,
        `Jazz`,
        `K-Pop`,
        `Latin`,
        `Metal`,
        `Piano`,
        `Pop`,
        `Rap`,
        `R&B`,
        `Soul`,
        `Reggae`,
        `Reggaeton`,
        `Rock`,
        `Techno`,
        `Trance`,
        `Trap`,
        `Triphop`,
        `World`
    ],
    FAVOURITE_GENRES_SEARCH: `Search for genres`,
    TAGS_LABEL: `TAGS`,
    TAGS: [
        `Producer`,
        `Songwriter`,
        `Singer-Songwriter`,
        `Singer`,
        `Musician`,
        `Band Member`,
        `MC`,
        `Artist`,
        `DJ`,
        `Jounalist`,
        `Podcaster`,
        `Enthusiast`,
        `Blogger`,
        `Executive`,
        `A&R`,
        `Publicist`,
        `Publisher`,
        `Influencer`,
        `Manager`,
        `Marketer`,
        `Host`,
        `Engineer`,
        `Casting Agent`,
        `Promoter`,
        `Composer`,
        `Music Supervisor`,
        `Rapper`,
        `Beatmaker`,
        `Fan`,
        `Concert Goer`,
        `College Student`,
        `Superfan`,
        `Industry Executive`,
        `Radio Professional`,
        `Vocal Coach`,
        `Music Coordinator`
    ],
    TAGS_SEARCH: `Search for tags`
}