export default {
    UPLOAD: "UPLOAD",
    COIN: "coins",
    RATER: "A&R Intern",
    SUBMIT_MUSIC_QUEUE: "Submit Music to the Queue",
    TITLE: "Title",
    UPLOAD_FILE: "Upload File",
    BROWSE: "browse",
    FILE: "file",
    SIZE: "10MB max",
    YOUTUBE_LINK: "Paste Youtube Link",
    GENRES_STYLES: "Genres & Styles",
    SEARCH_GENRES: "Search for Genres",
    SEARCH_STYLES: "Search for Style",
    PROMO_CODE: "Promo Code",
    RATING_HEADER: "Select # of Ratings",
    PLAN_A: "Plan A",
    LISTENERS: "Listeners",
    PLAN_B: "Plan B",
    CARD_INFORMATION: "Card Information",
    NAME: "Name",
    CARD_NUMBER: "Card Number",
    CARD_CVC: "CVC",
    CARD_MONTH: "MM/YY",
    PAYMENT_OPTIONS: "Payment Options",
    ORDER_NOW: "Order Now",
}