export default {
    NO_TWO_MONGULS : "No two moguls",
    ARE_ALIKE: "are alike!",
    THIS_WILL_HELP: `"This will help us share`,
    RIGHT_MUSIC: `the right music with you"`,
    DOB: "Date of Birth",
    LOCATION: "Location",
    CHOOSE_CITY: "Enter your Location",
    MM_DD_YYYY: "MM-DD-YYYY",
    GENDER: "Gender",
    ROLES: "Roles",
    SEARCH_ROLE: "Search for Roles",
    GENRES: "Genres",
    SEARCH_GENRES: "Search for Genres",
    CONTINUE: "Continue",
    STYLES: "Styles",
    SEARCH_STYLES: "Search for Styles",
}