export default {
    SUBCONTAINER2_LABEL: "ACCOUNT SETTINGS",
    SUBCONTAINER2_SUBLABEL1: "EMAIL ADDRESS",
    SUBCONTAINER2_PLACEHOLDER1: "Email address",
    SUBCONTAINER2_SUBLABEL2: "PASSWORD",
    SUBCONTAINER2_PLACEHOLDER2: "Type new password",
    SUBCONTAINER2_BUTTON_TEXT: "UPDATE PASSWORD",
};