export default {
    SUBCONTAINER2_LABEL: "ACCOUNT SETTINGS",
    SUBCONTAINER2_SUBLABEL1: "EMAIL ADDRESS",
    SUBCONTAINER2_PLACEHOLDER1: "Email address",
    SUBCONTAINER2_SUBLABEL2: "NEW PASSWORD",
    SUBCONTAINER2_PLACEHOLDER2: "Type new password",
    REPEAT_PASSWORD:"REPEAT PASSWORD",
    REPEAT_PASSWORD_PLACEHOLDER:"Repeat new password",
    SUBCONTAINER2_BUTTON_TEXT: "UPDATE",
};