export default {
    UPLOAD: "UPLOAD",
    COIN: "coins",
    RATER: "A&R Intern",
    UPGRADE_TO_PREMIUM: "Upgrade To Premium",
    PREMIUM_TEXT: "Pro memberships include instant access to upgraded benefits and historical analytics.  Cancel anytime.",
    PAYMENT_OPTIONS: "Payment Options",
    CARD_INFORMATION: "Card Information",
    NAME: "Name",
    CARD_NUMBER: "Card Number",
    CARD_CVC: "CVC",
    CARD_MONTH: "MM/YY",
    FOOTER_TEXT: "annual / auto-recurring / cancel anytime",
    SUBMIT_MUSIC: "Submit music to influencers",
    WITH_KEY: "(with key)",
    BASIC_MEMBER: "Basic members can only submit to the queue ",
    ACCESS_ADVANCE: "Access advanced track analytics ",
    BASIC_MEMBER_COMMENT: "Basic members do not see any comments ",
    GET_NOTIFIED: "Get notified when influencers need music ",
    GET_PRO_BADGE: "Get a Pro badge on your profile",
    RECEIVE_PRIORITY: "Receive priority support for all inquiries",
    LEVEL_UP: "Level up w/bonus coin & multiplier events ",
    MEMBERSHIP: "Membership Plan",
    MONTH: "month",
    YEAR: "year",
    MONTHLY: "monthly",
    YEARLY: "yearly",
    YEARLY_LABEL: "Upgrade $100/year",
    MONTHLY_LABEL: "Upgrade $15/month",
    BECAME: "BEACAME A ",
    BREAKER: "BREAKER",
    PRO: "PRO",
}