export default {
    UPLOAD: "UPLOAD",
    COIN: "coin",
    RATER: "rater",
    UPGRADE_TO_PREMIUM: "Upgrade To Premium",
    PREMIUM_TEXT: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem",
    PAYMENT_OPTIONS: "Payment Options",
    CARD_INFORMATION: "Card Information",
    NAME: "Name",
    CARD_NUMBER: "Card Number",
    CARD_CVC: "CVC",
    CARD_MONTH: "MM/YY",
    UPGRADE_LABEL: "Upgrade $99/month",
    FOOTER_TEXT: "annual / auto-recurring / cancel anytime",
}