export default {
    RESET_PASSWORD_HEADER: `RESET YOUR PASSWORD`,
    RESET_PASSWORD_SUBHEADER: `Choose a new password for your account.`,
    NEW_PASSWORD: `NEW PASSWORD`,
    REPEAT_NEW_PASSWORD: `REPEAT NEW PASSWORD`,
    RESET_PASSWORD: `RESET PASSWORD`
};