export default {
    BREAKER: "BREAKER",
    COIN: "coins",
    RATER: "A&R Intern",
    LISTEN: "Listen",
    DISCOVER_ARTIST: "Discover artists to help break",
    HEADER_TAG_TEXT: "The journey starts here",
    MULTIPLIER: "Multiplier",
    x2: "x2",
    SCORE_TRACK: "Score The Track",
    IMPRESSED_TEXT: "Are you impressed with the Artist?",
    SIGN_TEXT: "Would you sign this Artist?",
    IMPRESSED: "Impressed",
    NOT_IMPRESSED: "Not Impressed",
    SIGNED: "Signed",
    NOT_SIGNED: "Not Signed",
    GIVE_FEEDBACK: "Write Review",
    COMMENTS_HELP_CREATORS: "Comments Help Creators",
    POINTS_EARNED: "Points Earned",
}